### PR TITLE
Update tsconfig.json.md

### PR DESCRIPTION
**Pull request by staxmanade**
Fixing link

### CODE REVIEW

**Comment by mhegazy** [comment]
@DanielRosenwasser fixed the break to the site. do not think we need to update the link any more.

**Comment by staxmanade** [comment]
That doesn't work for me: http://www.typescriptlang.org/docs/handbook/tsconfig.json.html

shows

```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

**Comment by DanielRosenwasser** [comment]
Try http://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by staxmanade** [comment]
@DanielRosenwasser that is what is in this wiki Pull-request...

**Comment by mhegazy** [comment]
looks like i was confused. the fix was to make the menu point to the new link, not to make the old link valid again.

**Comment by DanielRosenwasser** [comment]
Again, sorry, I glanced at this really quickly. Busy day on my end. :smile:

**Comment by staxmanade** [comment]
All good!

**Comment by staxmanade** [comment]
If possible, I'd recommend seeing if you can 301 redirect the old link... lots of people probably link to it.

**Pull request merged**
