### PR TITLE
Update What's-new-in-TypeScript.md

### LINKED ISSUE #229: "What's new in TypeScript" wiki permalinks broken
The [wiki page for What's new in TypeScript](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript) is now gone/moved as it got too big for Github to render(#226).  That makes sense, but now all the bazillion links (like [this one for `readonly` tuples](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#readonly-tuples)) I and others have added to answers/comments on StackOverflow questions  are broken.  Would it be possible for the wiki page to be edited to preserve the existing permalinks?  I mean, even if the old link points to a nothing but another link to the same content hosted elsewhere (e.g., [pointing to an old revision](https://github.com/microsoft/TypeScript/wiki/What's-new-in-TypeScript/181ee76e7a8a5160dfd3ca7c334113d5955a1161#readonly-tuples)) so that the user has to click twice, it's better than just the current "this page has moved".   It would hopefully be small enough to actually render anyway.

Thoughts?  I would make a PR but I'm not sure if the code here is where the actual wiki code comes from (it seems out of date?).

### PR DESCRIPTION
**Pull request by jcalz**
Fixes #229

Links seem to work but I haven't checked them all yet

I wrote a silly node script
```ts
process.stdin.pipe(require('split')()).on('data', processLine);
let curVersion = "";
let anchors: { [k: string]: number } = {};
console.log("Because this page hit a limit on a GitHub wiki page size, it's now hosted on the website:");
console.log("https://www.typescriptlang.org/docs/handbook/release-notes/overview.html");
console.log("");
function processLine(line: string) {
    if (!line.startsWith("#"))
        return;
    let noAnchor = false;
    const verMatch = line.match(/^# TypeScript (.*)$/);
    if (verMatch) {
        curVersion = verMatch[1];
        anchors = {};
        noAnchor = true;
    }
    const anchor = line.
        replace(/^#+\s+/g, "").
        replace(/[^A-Z0-9 -]/gi, "").
        replace(/[^A-Z0-9]/gi, "-").
        toLowerCase();
    anchors[anchor] = (anchors[anchor] || 0);
    console.log(line);
    console.log("");
    const url = "https://www.typescriptlang.org/docs/handbook/release-notes/typescript-" +
        curVersion.replace(".", "-") + ".html" +
        (noAnchor ? "" : "#" + (anchor + (anchors[anchor] ? ("-" + anchors[anchor]) : "")));
    anchors[anchor]++;
    console.log("See [" + line.replace(/^#+\s+/g, "") + "](" + url + ")")
    console.log("");
}
```

and piped the [What's New from TS3.6](https://github.com/microsoft/TypeScript/wiki/What's-new-in-TypeScript/27b7d8b370e1cdcf9257435e5ddeb59bb9348989) into it, and got the thing here.

### CODE REVIEW

**Comment by jcalz** [comment]
I do notice a few broken links like [this one](https://github.com/microsoft/TypeScript-wiki/blob/77a8b2fec132c68e6568feaae18f839a034eb8d9/What's-new-in-TypeScript.md#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop), but it seems like these are due to discrepancies between the existing What's New doc and the release notes, such as typos.  Not sure how to deal with those other than one-off fixes as needed.

**Comment by jcalz** [comment]
Updated script:

```ts
process.stdin.pipe(require('split')()).on('data', processLine);
let curVersion = "";
let anchors: { [k: string]: number } = {};
console.log("Because this page hit a limit on a GitHub wiki page size, it's now hosted on the website:");
console.log("https://www.typescriptlang.org/docs/handbook/release-notes/overview.html");
console.log("");
function processLine(line: string) {
  if (!line.startsWith("#"))
    return;
  let noAnchor = false;
  const verMatch = line.match(/^# TypeScript (.*)$/);
  if (verMatch) {
    curVersion = verMatch[1];
    anchors = {};
    noAnchor = true;
  }
  const anchor = line.
    replace(/^#+\s+/g, "").
    replace(/[^A-Z0-9 -]/gi, "").
    replace(/[^A-Z0-9]/gi, "-").
    toLowerCase().
    replace("form-commonjs", "from-commonjs"); // ad-hoc fix
  anchors[anchor] = (anchors[anchor] || 0);

  if (curVersion === "2.7" && anchor === "example" && anchors[anchor] === 4) {
    anchors[anchor]++; // ad-hoc fix
  }

  console.log(line);
  console.log("");
  const url = "https://www.typescriptlang.org/docs/handbook/release-notes/typescript-" +
    curVersion.replace(".", "-") + ".html" +
    (noAnchor ? "" : "#" + (anchor + (anchors[anchor] ? ("-" + anchors[anchor]) : "")));
  anchors[anchor]++;
  console.log("See [" + line.replace(/^#+\s+/g, "") + "](" + url + ")")
  console.log("");
}
```

**Comment by orta** [comment]
Whoah, yeah - this is awesome work and a big improvement ❤️ thanks

I went and clicked on a bunch of random links and it all linked correctly for me. Great job.

**Comment by jcalz** [comment]
So does this somehow make its way to [the actual wiki](https://github.com/Microsoft/TypeScript/wiki) via some deployment process?

**Comment by orta** [comment]
Not to my knowledge, but these two files seem to have different histories:

https://github.com/microsoft/TypeScript/wiki/What's-new-in-TypeScript/_history
https://github.com/microsoft/TypeScript-wiki/commits/master/What's-new-in-TypeScript.md

**Comment by orta** [comment]
I've reached out to GitHub support

**Comment by jcalz** [comment]
I assume one who has write access to microsoft/TypesScript could modify the wiki there.  Not sure what, if anything, is keeping the wiki repo there related to this repo...

**Comment by jcalz** [comment]
I assume one who has write access to microsoft/TypeScript could modify the wiki there (meaning it looks like you could, if you wanted, just copy the contents of this file into the wiki, similar to [whatever you did before this](https://github.com/microsoft/TypeScript/wiki/What's-new-in-TypeScript/8985a92c5af3a078aae7d2b53583191d829b84c3)).  Not sure what, if anything, is keeping the wiki repo there related to this repo...

**Comment by jcalz** [comment]
@orta, could you go to the actual wiki and edit the file so that this version is there?  At least until whatever discrepancy with the deployment process is fixed or addressed?

**Pull request merged**
