### PR TITLE
Missing 'we' word in the 'Generics' doc

### PR DESCRIPTION
**Pull request by Gillespie59**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Thanks!

@RyanCavanaugh, we should discuss syncing documentation between the handbook and wiki at some point.

**Comment by Gillespie59** [comment]
Yes :+1:  for a way to sync both repo ;)

I have also another question. In the Handbook, I would like to move the "Errors" item from the menu at the last position. 

Because it is quiet strange to have this part at the middle of the documentation. 

But I can not find anywhere the TOC of the Handbook. And idea?

**Comment by Gillespie59** [comment]
For the sync of these two repos, maybe we should remove all duplicate content from the wiki repo, and add a hook (or with travis) in order to push to the wiki repo each commit done on the Handbook one.

**Comment by mhegazy** [comment]
+1

**Comment by mhegazy** [comment]
The +1 was for removing content from main repo and linking to this repo instead.

**Comment by DanielRosenwasser** [comment]
I agree with that idea as well, it seems like a duplication of effort.

@Gillespie59 can you clarify what you mean by "Errors"? Maybe a screenshot would help.

**Comment by Gillespie59** [comment]
Sorry for the dalay, I bookmarked your comment, but forgot to give an answer :(

Here a quick screenshot of what I mean by "Errors". In the menu of the Handbook, I want to move the "Common Errors" item at the end of the list.  In order to have all the TypeScript features first, and the "Common Errors" at the very end. 


image

**Comment by DanielRosenwasser** [comment]
Gotcha - ordering for these items will depend on how we plan to deploy the handbook, which @jonathandturner might know more about, but so far I've done work to get us using GitBook (https://github.com/Microsoft/TypeScript-Handbook/pull/47) and some stuff with Pandoc as well.

**Pull request merged**
