### PR TITLE
Getting the DTS from a JavaScript file example should replace .js to …

### PR DESCRIPTION
**Pull request by yuzhidi**
Getting the DTS from a JavaScript file example should replace .js to .d.ts

### CODE REVIEW

**Comment by orta** [comment]
The section title here is:

> ## Getting the DTS from a JavaScript file

So this does make sense in context.

**Comment by orta** [comment]
Thanks for trying to help

**Comment by yuzhidi** [comment]
original exmaple will not sucess, the input file is a JavaScript file, as title 'Getting the DTS from a JavaScript file', so where is a ts file name to replace?
```
- const dts = file.replace(".ts", ".d.ts")
+const dts = file.replace(".js", ".d.ts")
```

**Comment by yuzhidi** [comment]
> The section title here is:
> 
> > ## Getting the DTS from a JavaScript file
> 
> So this does make sense in context.

original exmaple will not sucess, the input file is a JavaScript file, as title 'Getting the DTS from a JavaScript file', so where is a ts file name to replace?
so the code should replace .js to .d.ts, not .ts do .d.ts

- const dts = file.replace(".ts", ".d.ts")
+const dts = file.replace(".js", ".d.ts")

**Comment by orta** [comment]
haha, good point

**Pull request merged**
